### ISSUE TITLE
how rayquery variant works?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_raytrace#14]
Hello. Please explain how rayquery variant of renderer works.
Created acceleration structure and used or so?
Where is no fully compute renderer with self-made bvh, not use vulkan acceleration structure?

**Comment by mklefrancois** [comment]
I think the best way to learn how the ray query feature is used, is to see how it is done in the ray tracing tutorial
* https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/tree/master/ray_tracing_rayquery
* https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/tree/master/ray_tracing_ao

In vk_raytrace, the acceleration structure is created in accelstruct.cpp and used by rtx_pipeline.cpp, rayquery.cpp and also by the  `nvvk::RayPickerKHR`. Ray query pipeline is simpler than RTX, but not as flexible. You can see that both pipelines are using the same shader code, only the entry point is different. For RQ the shader is pathtrace.comp, as it is only a compute shader.
