### ISSUE TITLE
Unused functions in shaders/punctual.glsl

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_raytrace#15]
Hi! For which purposes is declared functions
vec3 getPunctualRadianceSubsurface()
vec3 getPunctualRadianceTransmission()
vec3 getPunctualRadianceClearCoat()
vec3 getPunctualRadianceSheen()
but not used?
How to plan use it?

**Comment by mklefrancois** [comment]
There is a plan for using those, but didn't had the time yet.
