### ISSUE TITLE
error compiling rgen shader:

### ISSUE THREAD

**Issue by pprabhu78** [nvpro-samples/vk_raytrace#16]
I get a compilation error for just this shader:

1>Generating D:/poojan/projects/nvpro-samples/vk_raytrace/autogen/pathtrace.rgen.spv
1>C:/VulkanSDK/1.2.189.2/bin/glslangValidator.exe -g --target-env vulkan1.2 -o D:/poojan/projects/nvpro-samples/vk_raytrace/autogen/pathtrace.rgen.spv D:/poojan/projects/nvpro-samples/vk_raytrace/shaders/pathtrace.rgen
1>D:/poojan/projects/nvpro-samples/vk_raytrace/shaders/pathtrace.rgen
1>CUSTOMBUILD : error : D:/poojan/projects/nvpro-samples/vk_raytrace/shaders/traceray_rtx.glsl:46: 'no rayPayloadEXT/rayPayloadInEXT declared' : with layout(location = 0)
1>CUSTOMBUILD : error : D:/poojan/projects/nvpro-samples/vk_raytrace/shaders/random.glsl:34: '' :  syntax error, unexpected UINT, expecting COMMA or SEMICOLON
1>CUSTOMBUILD : error : 2 compilation errors.  No code generated.

Ofcourse, if I don't compile that shader, the sample runs (atleast the compute pipeline works as expected), so I suspect it's probably something different with my validator/version/sdk.

I twiddled around a lot with moving code, etc. No luck. I can't seem to understand what is so different than say the ray tracing gltf sample (all the samples except this one compile/run fine incidentally)

Any ideas?

**Comment by mklefrancois** [comment]
Hi @pprabhu78, I pulled up the latest version and compiled it using Vulkan SKD 1.2.198.0 and did not encounter the issue. One thing that surprises me, is the fact that in your version, it tries to create a `.spv` file. This was changed a long time ago to `header` as you can see here:

```
  C:/VulkanSDK/1.2.198.0/bin/glslangValidator.exe -g --target-env vulkan1.2 --vn pathtrace_rgen -o F:/nvpro-samples/Git
  Hub/vk_raytrace/autogen/pathtrace.rgen.h F:/nvpro-samples/GitHub/vk_raytrace/shaders/pathtrace.rgen
```

Can you check if you have the top of the tree? Check also the dependency on the [`nvpro_core`](https://github.com/nvpro-samples/nvpro_core) project.

**Comment by pprabhu78** [comment]
Hi,
So, it seems for some reason I had replaced the validator in the vulkan sdk, with one I built on my own about 5 months ago. I have completely forgotten why :/

I reverted it and it is working. Apologies. I guess what stumped me was that the other samples were working.

edit: closing issue
