### ISSUE TITLE
How to build from source on MSYS2 MINGW64?

### ISSUE THREAD

**Issue by ghost** [nvpro-samples/vk_raytrace#24]
cmake configuration failed:

```
$ cmake ..
-- Building for: Ninja
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- -------------------------------
-- Processing Project vk_raytrace:
CMake Error at CMakeLists.txt:30 (find_path):
  Could not find BASE_DIRECTORY using the following files:
  nvpro_core/cmake/setup.cmake


-- Configuring incomplete, errors occurred!

```

**Comment by tigrazone** [comment]
Try 
cmake .. -G "Unix Makefiles"
and build by
make

**Comment by ghost** [comment]
> Try cmake .. -G "Unix Makefiles" and build by make

Still the same error message.

**Comment by tigrazone** [comment]
I use cmake installed in windows, not in msys. And I call from msys prompt
/c/cmake/bin/cmake .. -G "Unix Makefiles"
and all built ok without errors.
maybe it helps

**Comment by ghost** [comment]
> I use cmake installed in windows, not in msys. And I call from msys prompt /c/cmake/bin/cmake .. -G "Unix Makefiles" and all built ok without errors. maybe it helps

Please test on the MSYS2 MINGW64 Shell.

**Comment by tigrazone** [comment]
I do it always and my method works. I dont like to solve settings. Just works
