### ISSUE TITLE
Change settings panel

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_raytrace#29]
Hello.
I cant find in code
- how to make panel fixed width in pixels
- how to start renderer with floating panel, not docked
- how to save panel states between renderer runs

**Comment by mklefrancois** [comment]
This would require a refactoring of the code. Something I've been thinking about for a while, but haven't done yet.
To see what it would look like, this project was reactor: [vk_shaded_gltfscene ](https://github.com/nvpro-samples/vk_shaded_gltfscene).

And all samples in [vk_mini_samples ](https://github.com/nvpro-samples/vk_mini_samples) have the ability to have dock panels, and floating windows as well. One that show it well is the [realtime_analysis](https://github.com/nvpro-samples/vk_mini_samples/tree/main/samples/realtime_analysis). 

Saving state of the docking window can be seen in the `addSettingsHandler()` function of the `Element`. See for example, [this exemple](https://github.com/nvpro-samples/nvpro_core/blob/ae627159d37109864365b9b573736c6afcbafb27/nvvkhl/element_logger.hpp#L240C8-L240C28).
