### ISSUE TITLE
CMakeLists.txt Target Link Libraries Incomplete

### ISSUE THREAD

**Issue by chrisdonlan** [nvpro-samples/vk_raytrace#5]
The issue was: both `libdl` and `pthreads` were missing.  I am not sure what the optimal route would be in the context of the overall tutorial/example system.  But, I got things working with the following change in `CMakeLists.txt` circa line 151 (the `Linkage` section): 

From:
```
 #####################################################################################
# Linkage
#
target_link_libraries(${PROJNAME} ${PLATFORM_LIBRARIES} shared_sources)
```
To:
```
#####################################################################################
# Linkage
#
find_package(Threads REQUIRED)
set(PROJECT_LIBRARIES ${CMAKE_DL_LIBS} -lpthread)
target_link_libraries(${PROJNAME} ${PLATFORM_LIBRARIES}  ${PROJECT_LIBRARIES} shared_sources)
```

**Comment by mklefrancois** [comment]
We have done a big re-factor for Linux and hopefully the error you had is now resolved. 
Please feel free to re-open if there is still an issue.
