### ISSUE TITLE
Supportted GPU

### ISSUE THREAD

**Issue by cybergamechanger** [nvpro-samples/vk_raytrace#6]
This works on Jetson nano or xavier?

**Comment by NBickford-NV** [comment]
Hi Alexander! This requires a GPU with support for hardware-accelerated ray tracing (specifically Vulkan ray tracing pipelines) - I don't think Jetson Nano or Xavier support this. ~~They'll most likely be able to use ray tracing via OptiX, though!~~ (edit: unfortunately not at the moment; see [comment below](https://github.com/nvpro-samples/vk_raytrace/issues/6#issuecomment-783623783))

**Comment by NBickford-NV** [comment]
Ah, it turns out I was wrong about this (I was confused with GVDB) - Detlef Roettger corrects me offline that we don't have an OptiX SDK for the ARM architecture (including Jetson Nano and Xavier) at this time. Sorry about that!

**Comment by cybergamechanger** [comment]
Thank you @NeilBickford-NV.
